---
title: "Map_function"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages(c("ggplot2", "devtools", "dplyr", "stringr"))

# some standard map packages.
install.packages(c("maps", "mapdata"))

# the github version of ggmap, which recently pulled in a small fix I had
# for a bug 
devtools::install_github("dkahle/ggmap")
install.packages("tools")
```
```{r}

```



```{r}
  library(ggplot2)
  library(ggmap)
  library(maps)
  library(mapdata)
  library(stringr)
  library(dplyr)
  library(tools)
  library(readr)
map_distribution=function(dataframe,rate){
  states= map_data("state")
  states$region=toTitleCase(states$region)
  state_distribution=inner_join(states, dataframe, by = "region")
  ggplot(data = state_distribution) + 
  geom_polygon(aes(x = long, y = lat, fill = rate, group = group,show.legend = TRUE), color = "white") + coord_fixed(1.3) +guides(fill=FALSE) 
 
}


```



```{r}

lung_cancer <- read.csv("~/1560/lung cancer.csv")
map_distribution(lung_cancer,"Rate")
View(states)
```
```{r}
states<- map_data("state")
states$region=toTitleCase(states$region)
state_distribution <- inner_join(states, lung_cancer, by = "region")
ggplot(data = state_distribution) + 
  geom_polygon(aes(x = long, y = lat, fill = Rate, group = group,show.legend = TRUE), color = "white") + coord_fixed(1.3) +guides(fill=FALSE) 
 
```



